name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore pwexport/pwexport.csproj

    - name: Build project
      run: dotnet build pwexport/pwexport.csproj --configuration Release --no-restore

    - name: Publish for Windows
      run: dotnet publish pwexport/pwexport.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true

    - name: Publish for macOS
      run: dotnet publish pwexport/pwexport.csproj -c Release -r osx-x64 --self-contained -p:PublishSingleFile=true

    - name: Publish for Linux
      run: dotnet publish pwexport/pwexport.csproj -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v4
      with:
        name: windows-publish
        path: |
          pwexport/bin/Release/net8.0/win-x64/publish/

    - name: Upload artifact for macOS
      uses: actions/upload-artifact@v4
      with:
        name: macos-publish
        path: |
          pwexport/bin/Release/net8.0/osx-x64/publish/

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v4
      with:
        name: linux-publish
        path: |
          pwexport/bin/Release/net8.0/linux-x64/publish/